// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhraxtbkcbvrzhlnoyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaHJheHRia2NidnJ6aGxub3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNzcyNTUsImV4cCI6MjA1Mzc1MzI1NX0.J8DYk54Vi2OGI1Jgb6ayBAniPMzMSXKMqVZbM3pqYwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);